/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_studiohartman_jamepad_Main */

#ifndef _Included_com_studiohartman_jamepad_Main
#define _Included_com_studiohartman_jamepad_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_studiohartman_jamepad_Main
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_studiohartman_jamepad_Main_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
