/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_studiohartman_jamepad_Main */

#ifndef _Included_com_studiohartman_jamepad_Main
#define _Included_com_studiohartman_jamepad_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_studiohartman_jamepad_Main
 * Method:    nativeInitSDLGamepad
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_studiohartman_jamepad_Main_nativeInitSDLGamepad
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_studiohartman_jamepad_Main
 * Method:    getNumRollers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_studiohartman_jamepad_Main_getNumRollers
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
